package com.example.opensonggoogletvviewer.model

data class AppStrings(
    val appTitle: String,
    val searching: String,
    val discoveryError: String,
    val language: String,
    val colorScheme: String,
    val dark: String,
    val light: String,
    val refreshRate: String,
    val refreshRateQuicker: String,
    val refreshRateRegular: String,
    val refreshRateSlower: String,
    val refreshRateSlow: String,
    val refreshServers: String,
    val servers: String,
    val noServersFound: String,
    val selectServer: String,
    val connected: String,
    val noPresentationRunning: String,
    val connecting: String,
    val error: String,
)

fun stringsFor(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.Czech -> AppStrings(
            appTitle = "OpenSong Viewer",
            searching = "Hled\u00e1m OpenSong servery...",
            discoveryError = "Chyba hled\u00e1n\u00ed",
            language = "Jazyk",
            colorScheme = "Barevn\u00e9 sch\u00e9ma",
            dark = "Tmav\u00e9",
            light = "Sv\u011btl\u00e9",
            refreshRate = "Rychlost obnovy",
            refreshRateQuicker = "Rychlej\u0161\u00ed",
            refreshRateRegular = "B\u011b\u017en\u00e1",
            refreshRateSlower = "Pomalej\u0161\u00ed",
            refreshRateSlow = "Pomal\u00e1",
            refreshServers = "Obnovit servery",
            servers = "Servery",
            noServersFound = "\u017d\u00e1dn\u00fd server nebyl nalezen.",
            selectServer = "Vyberte OpenSong server",
            connected = "P\u0159ipojeno",
            noPresentationRunning = "P\u0159ipojeno, prezentace neb\u011b\u017e\u00ed",
            connecting = "P\u0159ipojuji...",
            error = "Chyba",
        )
        AppLanguage.Slovak -> AppStrings(
            appTitle = "OpenSong Viewer",
            searching = "H\u013ead\u00e1m OpenSong servery...",
            discoveryError = "Chyba h\u013eadania",
            language = "Jazyk",
            colorScheme = "Farebn\u00e1 sch\u00e9ma",
            dark = "Tmav\u00e1",
            light = "Svetl\u00e1",
            refreshRate = "R\u00fdchlos\u0165 obnovy",
            refreshRateQuicker = "R\u00fdchlej\u0161ia",
            refreshRateRegular = "Be\u017en\u00e1",
            refreshRateSlower = "Pomal\u0161ia",
            refreshRateSlow = "Pomal\u00e1",
            refreshServers = "Obnovi\u0165 servery",
            servers = "Servery",
            noServersFound = "Nena\u0161iel sa \u017eiadny server.",
            selectServer = "Vyberte OpenSong server",
            connected = "Pripojen\u00e9",
            noPresentationRunning = "Pripojen\u00e9, prezent\u00e1cia nebe\u017e\u00ed",
            connecting = "Prip\u00e1jam...",
            error = "Chyba",
        )
        AppLanguage.English -> AppStrings(
            appTitle = "OpenSong Viewer",
            searching = "Searching for OpenSong servers...",
            discoveryError = "Discovery error",
            language = "Language",
            colorScheme = "Color scheme",
            dark = "Dark",
            light = "Light",
            refreshRate = "Refresh rate",
            refreshRateQuicker = "Quicker",
            refreshRateRegular = "Regular",
            refreshRateSlower = "Slower",
            refreshRateSlow = "Slow",
            refreshServers = "Refresh servers",
            servers = "Servers",
            noServersFound = "No servers found.",
            selectServer = "Select OpenSong server",
            connected = "Connected",
            noPresentationRunning = "Connected, no presentation running",
            connecting = "Connecting...",
            error = "Error",
        )
    }
}
